t rebase --continue To https://github.com/MandeqAli/FlutterProject.git  ! [rejected]        main -> main (fetch first)  erProject.git'  hint: Updates were rejected because the remote contains work that you  do not  hint: have locally. This is usually caused by another repository  pushing to  hint: the same ref. If you want to integrate the remote changes, use  hint: 'git pull' before pushing again.  hint: See the 'Note about fast-forwards' in 'git push --help' for  details.  PS C:\Users\GH\FlutterProject> git pull origin main --rebase  >>  remote: Enumerating objects: 75, done.  remote: Counting objects: 100% (33/33), done.  remote: Compressing objects: 100% (9/9), done.  remote: Total 75 (delta 26), reused 24 (delta 24), pack-reused 42 (from  1)  Unpacking objects: 100% (75/75), 31.45 KiB | 79.00 KiB/s, done.  From https://github.com/MandeqAli/FlutterProject   * branch            main       -> FETCH_HEAD      63dfb12..b1598b1  main       -> origin/main      Auto-merging lib/main.dart      CONFLICT (content): Merge conflict in lib/main.dart      Auto-merging pubspec.yaml      CONFLICT (content): Merge conflict in pubspec.yaml      hint: Resolve all conflicts manually, mark them as resolved with      hint: "git add/rm <conflicted_files>", then run "git rebase      --continue".      hint: You can instead skip this commit: run "git rebase --skip".      hint: To abort and get back to the state before "git rebase", run      "git rebase --abort".      hint: Disable this message with "git config set      advice.mergeConflict false"      Could not apply 5b7fae6... # SCRUM-17      PS C:\Users\GH\FlutterProject> git push origin main      >>      To https://github.com/MandeqAli/FlutterProject.git      error: failed to push some refs to      'https://github.com/MandeqAli/FlutterProject.git'      hint: Updates were rejected because a pushed branch tip is behind      its      remote      hint: counterpart. If you want to integrate the remote changes, use      'ghint: before pushing again.      hint: See the 'Note about fast-forwards' in 'git push --help' for      details.      PS C:\Users\GH\FlutterProject> git pull origin main --rebase      error: Pulling is not possible because you have unmerged files.      hint: Fix them up in the work tree, and then use 'git add/rm      <file>'      hint: as appropriate to mark resolution and make a commit.      fatal: Exiting because of an unresolved conflict.      >>      t rebase --continue      SCRUM-17
     # Conflicts:
     #       lib/main.dart
     #       pubspec.yaml

     # Please enter the commit message for your changes. Lines starting
     # with '#' will be ignored, and an empty message aborts the commit.
     #
     .git/COMMIT_EDITMSG[+] [unix] (07:38 07/02/2026)               2,1
     Top-- INSERT --To https://github.com/MandeqAli/FlutterProject.git
      ! [rejected]        main -> main (fetch first)
      erProject.git'
      hint: Updates were rejected because the remote contains work that
      you
      do not
      hint: have locally. This is usually caused by another repository
      pushing to
      hint: the same ref. If you want to integrate the remote changes,
      use
      hint: 'git pull' before pushing again.
      hint: See the 'Note about fast-forwards' in 'git push --help' for
      details.
      PS C:\Users\GH\FlutterProject> git pull origin main --rebase
      >>
      remote: Enumerating objects: 75, done.
      remote: Counting objects: 100% (33/33), done.
      remote: Compressing objects: 100% (9/9), done.
      remote: Total 75 (delta 26), reused 24 (delta 24), pack-reused 42
      (from 1)
      Unpacking objects: 100% (75/75), 31.45 KiB | 79.00 KiB/s, done.
      From https://github.com/MandeqAli/FlutterProject
       * branch            main       -> FETCH_HEAD
          63dfb12..b1598b1  main       -> origin/main
	  Auto-merging lib/main.dart
	  CONFLICT (content): Merge conflict in lib/main.dart
	  Auto-merging pubspec.yaml
	  CONFLICT (content): Merge conflict in pubspec.yaml
	  hint: Resolve all conflicts manually, mark them as resolved
	  with
	  hint: "git add/rm <conflicted_files>", then run "git rebase
	  --continue".
	  hint: You can instead skip this commit: run "git rebase
	  --skip".
	  hint: To abort and get back to the state before "git rebase",
	  run "git rebase --abort".
	  hint: Disable this message with "git config set
	  advice.mergeConflict false"
	  Could not apply 5b7fae6... # SCRUM-17
	  PS C:\Users\GH\FlutterProject> git push origin main
	  >>
	  To https://github.com/MandeqAli/FlutterProject.git
	  error: failed to push some refs to
	  'https://github.com/MandeqAli/FlutterProject.git'
	  hint: Updates were rejected because a pushed branch tip is
	  behind its
	  remote
	  hint: counterpart. If you want to integrate the remote
	  changes, use 'ghint: before pushing again.
	  hint: See the 'Note about fast-forwards' in 'git push --help'
	  for details.
	  PS C:\Users\GH\FlutterProject> git pull origin main --rebase
	  error: Pulling is not possible because you have unmerged
	  files.
	  hint: Fix them up in the work tree, and then use 'git add/rm
	  <file>'
	  hint: as appropriate to mark resolution and make a commit.
	  fatal: Exiting because of an unresolved conflict.
	  >>
	  t rebase --continue
	  SCRUM-17

	  # Conflicts:
	  #       lib/main.dart
	  #       pubspec.yaml

	  # Please enter the commit message for your changes. Lines
	  starting
	  # with '#' will be ignored, and an empty message aborts the
	  commit.
	  #
	  .git/COMMIT_EDITMSG[+] [unix] (07:38 07/02/2026)
	  2,1 Top-- INSERT --To
	  https://github.com/MandeqAli/FlutterProject.git
	   ! [rejected]        main -> main (fetch first)
	   erProject.git'
	   hint: Updates were rejected because the remote contains work
	   that you
	   do not
	   hint: have locally. This is usually caused by another
	   repository pushing to
	   hint: the same ref. If you want to integrate the remote
	   changes, use
	   hint: 'git pull' before pushing again.
	   hint: See the 'Note about fast-forwards' in 'git push --help'
	   for details.
	   PS C:\Users\GH\FlutterProject> git pull origin main --rebase
	   >>
	   remote: Enumerating objects: 75, done.
	   remote: Counting objects: 100% (33/33), done.
	   remote: Compressing objects: 100% (9/9), done.
	   remote: Total 75 (delta 26), reused 24 (delta 24),
	   pack-reused 42 (from 1)
	   Unpacking objects: 100% (75/75), 31.45 KiB | 79.00 KiB/s,
	   done.
	   From https://github.com/MandeqAli/FlutterProject
	    * branch            main       -> FETCH_HEAD
	       63dfb12..b1598b1  main       -> origin/main
	       Auto-merging lib/main.dart
	       CONFLICT (content): Merge conflict in lib/main.dart
	       Auto-merging pubspec.yaml
	       CONFLICT (content): Merge conflict in pubspec.yaml
	       hint: Resolve all conflicts manually, mark them as
	       resolved with
	       hint: "git add/rm <conflicted_files>", then run "git
	       rebase --continue".
	       hint: You can instead skip this commit: run "git rebase
	       --skip".
	       hint: To abort and get back to the state before "git
	       rebase", run "git rebase --abort".
	       hint: Disable this message with "git config set
	       advice.mergeConflict false"
	       Could not apply 5b7fae6... # SCRUM-17
	       PS C:\Users\GH\FlutterProject> git push origin main
	       >>
	       To https://github.com/MandeqAli/FlutterProject.git
	       error: failed to push some refs to
	       'https://github.com/MandeqAli/FlutterProject.git'
	       hint: Updates were rejected because a pushed branch tip
	       is behind its
	       remote
	       hint: counterpart. If you want to integrate the remote
	       changes, use 'ghint: before pushing again.
	       hint: See the 'Note about fast-forwards' in 'git push
	       --help' for details.
	       PS C:\Users\GH\FlutterProject> git pull origin main
	       --rebase
	       error: Pulling is not possible because you have unmerged
	       files.
	       hint: Fix them up in the work tree, and then use 'git
	       add/rm <file>'
	       hint: as appropriate to mark resolution and make a
	       commit.
	       fatal: Exiting because of an unresolved conflict.
	       >>
	       t rebase --continue
	       SCRUM-17

	       # Conflicts:
	       #       lib/main.dart
	       #       pubspec.yaml

	       # Please enter the commit message for your changes. Lines
	       starting
	       # with '#' will be ignored, and an empty message aborts
	       the commit.
	       #
	       .git/COMMIT_EDITMSG[+] [unix] (07:38 07/02/2026)
	       2,1 Top-- INSERT --To
	       https://github.com/MandeqAli/FlutterProject.git
	        ! [rejected]        main -> main (fetch first)
		erProject.git'
		hint: Updates were rejected because the remote contains
		work that you
		do not
		hint: have locally. This is usually caused by another
		repository pushing to
		hint: the same ref. If you want to integrate the remote
		changes, use
		hint: 'git pull' before pushing again.
		hint: See the 'Note about fast-forwards' in 'git push
		--help' for details.
		PS C:\Users\GH\FlutterProject> git pull origin main
		--rebase
		>>
		remote: Enumerating objects: 75, done.
		remote: Counting objects: 100% (33/33), done.
		remote: Compressing objects: 100% (9/9), done.
		remote: Total 75 (delta 26), reused 24 (delta 24),
		pack-reused 42 (from 1)
		Unpacking objects: 100% (75/75), 31.45 KiB | 79.00
		KiB/s, done.
		From https://github.com/MandeqAli/FlutterProject
		 * branch            main       -> FETCH_HEAD
		    63dfb12..b1598b1  main       -> origin/main
		    Auto-merging lib/main.dart
		    CONFLICT (content): Merge conflict in lib/main.dart
		    Auto-merging pubspec.yaml
		    CONFLICT (content): Merge conflict in pubspec.yaml
		    hint: Resolve all conflicts manually, mark them as
		    resolved with
		    hint: "git add/rm <conflicted_files>", then run "git
		    rebase --continue".
		    hint: You can instead skip this commit: run "git
		    rebase --skip".
		    hint: To abort and get back to the state before "git
		    rebase", run "git rebase --abort".
		    hint: Disable this message with "git config set
		    advice.mergeConflict false"
		    Could not apply 5b7fae6... # SCRUM-17
		    PS C:\Users\GH\FlutterProject> git push origin main
		    >>
		    To https://github.com/MandeqAli/FlutterProject.git
		    error: failed to push some refs to
		    'https://github.com/MandeqAli/FlutterProject.git'
		    hint: Updates were rejected because a pushed branch
		    tip is behind its
		    remote
		    hint: counterpart. If you want to integrate the
		    remote changes, use 'ghint: before pushing again.
		    hint: See the 'Note about fast-forwards' in 'git
		    push --help' for details.
		    PS C:\Users\GH\FlutterProject> git pull origin main
		    --rebase
		    error: Pulling is not possible because you have
		    unmerged files.
		    hint: Fix them up in the work tree, and then use
		    'git add/rm <file>'
		    hint: as appropriate to mark resolution and make a
		    commit.
		    fatal: Exiting because of an unresolved conflict.
		    >>
		    t rebase --continue
		    SCRUM-17

		    # Conflicts:
		    #       lib/main.dart
		    #       pubspec.yaml

		    # Please enter the commit message for your changes.
		    Lines starting
		    # with '#' will be ignored, and an empty message
		    aborts the commit.
		    #
		    .git/COMMIT_EDITMSG[+] [unix] (07:38 07/02/2026)
		    2,1 Top-- INSERT -
		   SCRUM-17